Repository stratis-storage/devicemapper-rs, pull requests merged in 2018-02, with the labels that each got.

#264 Update nix to v0.10.0
  Cargo.toml
  src/device.rs
  src/thindev.rs
Labels: review-final

#267 Document events
  src/dm.rs
  src/lib.rs
Labels: review-final

#269 Establish a separate minimal_cachedev() method for testing
  src/cachedev.rs
  src/lib.rs
Labels: review-final

#270 Change ThinDev::snapshot to take an optional uuid
  src/thindev.rs
Labels: review-final, trivial

#273 Specify writethrough feature argument
  src/cachedev.rs
Labels: review-final

#272 Add a set_cache_table method to CacheDev
  src/cachedev.rs
Labels: review-final

#277 Allow some clippy errors caused by bitflags! macro
  src/dm.rs
Labels: review-final

#276 Pass arguments to CacheDev::gen_default_table in proper order
  src/cachedev.rs
Labels: bug, in progress

#281 Add a more precise condition in list_devices test
  src/dm.rs
Labels: review-final, trivial
